### PR TITLE
Update Get-AzureADGraphApps.ps1

### PR DESCRIPTION
**Pull request by marshallwp**
Add #Requires statement to prevent the script from running on incompatible PowerShell versions.

### CODE REVIEW

**Review by hkystar35 — APPROVED** [review]
Looks good to me

**Comment by Wittionary** [comment]
@BinaryWizard904
Glad to see this PR is here. Just spent wayyy too much time waiting for dependencies to load.

@merill @dhruvchand @jeevansd
Can this be merged sooner than later? Issues will see an uptick as the deadline looms and admins seek to proactively migrate APIs.

**Comment by Wittionary** [comment]
You're the man, @dhruvchand !!

**Comment by dhruvchand** [comment]
Thanks @BinaryWizard904 for the PR, and @Wittionary and @hkystar35 for the quick reviews!

**Pull request merged**
